### ISSUE TITLE
[PyPI] ModuleNotFoundError: No module named 'portable_wisdom'

### ISSUE THREAD

**Issue by tsuyo-o** [jacobbudin/portable-wisdom#22]
When I executed  "portable-wisdom -h" after installing the package via pip, I got the "Module not found" error.
It looks all the codes of this library are located right under "site-packages" directory.
After creating "portable_wisdom" directory under "site-packages" and coping the codes to the directory, it became functional.
Could you confirm if it's reproducible on your side?
My environment is Linux/Python 3.11/venv.

**Comment by jacobbudin** [comment]
@tsuyo-o Sorry. That's a blooper. Can you try the latest release (v1.0.1) I just published?

**Comment by tsuyo-o** [comment]
@jacobbudin confirmed it's working. Thank you!
